### ISSUE TITLE
Getting AndroidX working with this library

### ISSUE THREAD

**Issue by exts** [matthew-carroll/fluttery_audio#21]
Steps I took to get this working in a release build.

1. First open flutter project in android in a new window then attempt to convert to an androidx project from the refactor menu

2. Change dependencies of this library to

```
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.annotation:annotation:1.0.2'
```

3. Change sdk version to `compileSdkVersion 28`

4. Open all java files and replace `import android.support.annotation.NonNull;` with `import androidx.annotation.NonNull;`

5. Rebuild -> Close project

6. Run `flutter build apk`

Hope that helps someone.

**Comment by DeanShepherdson** [comment]
Currently having the same issue. By "all java files" do you mean in the project java files, or in the package java files?

**Comment by exts** [comment]
@DeanShepherdson every file that has the incorrect support library in this package

**Comment by elmarou** [comment]
I use the flutter_audio plugin at first it works properly then I encountered this error which stops my application completely 

can you help me @exts 

```dart
Android -> Flutter: onBufferingUpdate()
E/AndroidRuntime(29083): FATAL EXCEPTION: AudioPlayer
E/AndroidRuntime(29083): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AudioPlayer
E/AndroidRuntime(29083):     at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(29083):     at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime(29083):     at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime(29083):     at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/AndroidRuntime(29083):     at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(29083):     at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(29083):     at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(29083):     at io.fluttery.flutteryaudio.FlutteryAudioPlugin$1.onPlayerPlaybackUpdate(FlutteryAudioPlugin.java:83)
E/AndroidRuntime(29083):     at io.fluttery.flutteryaudio.AudioPlayer$1.run(AudioPlayer.java:218)
E/AndroidRuntime(29083):     at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(29083):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29083):     at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(29083):     at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by exts** [comment]
@elmarou that goes beyond my java knowledge. Maybe these links can help you:

<https://github.com/flutter/flutter/issues/32315>
<https://github.com/aloisdeniel/flutter_geocoder/issues/18>

**Comment by elmarou** [comment]
@exts  it's not a java error that an error causes the compatibility of the plugin flutter_audio 
i`m on androidX

**Comment by exts** [comment]
Don't know what to tell you, I didn't get that error when I made those
changes

**Comment by vijaykanta** [comment]
There is a source end point for the package to be set in pubspec yaml file that you can use to update the package and it will work out of the box. Check here.

https://github.com/aloisdeniel/flutter_geocoder/pull/15#issuecomment-510159764
