### ISSUE TITLE
Android app crashes when audio starts playing

### ISSUE THREAD

**Issue by doodlezucc** [matthew-carroll/fluttery_audio#26]
Whenever I try to set the `playbackState` of an `Audio` widget to `PlaybackState.playing`, my app crashes as soon as the audio is done buffering. The sound is played in its full length, though.

I'm using the latest release of fluttery_audio and the following as my `audioUrl`: https://audiodemos.github.io/vctk_set0/ground_truth.wav

Console log:
```
D/FlutteryAudioPlugin( 4746): Flutter -> Android: audioplayer/demo_player/activate_visualizer
D/FlutteryAudioPlugin( 4746): AudioPlayerCall - Player ID: demo_player, Command: activate_visualizer
D/FlutteryAudioPlugin( 4746): Flutter -> Android: audioplayer/demo_player/load
D/FlutteryAudioPlugin( 4746): AudioPlayerCall - Player ID: demo_player, Command: load
D/FlutteryAudioPlugin( 4746): Loading new audio.
D/AudioPlayer( 4746): load()
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onAudioLoading()
D/MediaHTTPConnection( 4746): filterOutInternalHeaders: key=User-Agent, val= SonyD5803 Build/23.5.A.1.291 stagefright/1.2 (Linux;Android 6.0.1)
D/MediaHTTPConnection( 4746): filterOutInternalHeaders: key=x-wap-profile, val= http://uaprof.sonymobile.com/D5803R2331.xml
D/MediaHTTPConnection( 4746): proxy null port 0
W/System  ( 4746): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
D/AudioPlayer( 4746): onBufferingUpdate(): 50%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer( 4746): onBufferingUpdate(): 50%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer( 4746): onBufferingUpdate(): 67%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer( 4746): onBufferingUpdate(): 84%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer( 4746): onBufferingUpdate(): 84%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer( 4746): onBufferingUpdate(): 100%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
D/MediaPlayer( 4746): setSubtitleAnchor in MediaPlayer
D/AudioPlayer( 4746): onPrepared()
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onAudioReady()
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onPlayerPaused()
D/FlutteryAudioPlugin( 4746): Flutter -> Android: audioplayer/demo_player/play
D/FlutteryAudioPlugin( 4746): AudioPlayerCall - Player ID: demo_player, Command: play
D/FlutteryAudioPlugin( 4746): Playing audio
D/AudioPlayer( 4746): play()
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onPlayerPlaying()
D/AudioPlayer( 4746): onBufferingUpdate(): 100%
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onBufferingUpdate()
E/AndroidRuntime( 4746): FATAL EXCEPTION: AudioPlayer
E/AndroidRuntime( 4746): Process: com.example.audiotest, PID: 4746
E/AndroidRuntime( 4746): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AudioPlayer
E/AndroidRuntime( 4746): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime( 4746): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
E/AndroidRuntime( 4746): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime( 4746): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
E/AndroidRuntime( 4746): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime( 4746): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime( 4746): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime( 4746): 	at io.fluttery.flutteryaudio.FlutteryAudioPlugin$1.onPlayerPlaybackUpdate(FlutteryAudioPlugin.java:83)
E/AndroidRuntime( 4746): 	at io.fluttery.flutteryaudio.AudioPlayer$1.run(AudioPlayer.java:218)
E/AndroidRuntime( 4746): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4746): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4746): 	at android.os.Looper.loop(Looper.java:234)
E/AndroidRuntime( 4746): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/art     ( 4746): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[13,tid=4806,Native,Thread*=0x9f52b300,peer=0x12d620a0,"Thread-16558"]
D/AudioPlayer( 4746): onCompletion()
D/FlutteryAudioPlugin( 4746): Android -> Flutter: onPlayerCompleted()
D/FlutterNativeView( 4746): FlutterView.send called on a detached view, channel=fluttery_audio
I/Process ( 4746): Sending signal. PID: 4746 SIG: 9
Lost connection to device.
```

flutter doctor:
```
[√] Flutter (Channel beta, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale de-DE)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\elect\.flutter\flutter
    • Framework revision 20e59316b8 (2 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\elect\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[!] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • D5803 • YT9113VVY9 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```

**Comment by kannanseeni** [comment]
for me also the same issue in Android. using Flutter 1.7. 
Working well with IOS

**Comment by arthurb123** [comment]
Having the same issue, using SDK >=2.1.0 <3.0.0 with the latest version of fluttery_audio.

**Comment by rowild** [comment]
Another Flutter package, "flutter_sound", had the same problem, but seems to have fixed it:
https://github.com/dooboolab/flutter_sound/issues/93

I am not a java dev, but if there is anybody else here around, who is fit with Java, maybe this is a hint to a possible solution for the fluttery_audio? Hope, someone can fix the issue and post the results here...

**Comment by amrabdalkrim** [comment]
When you play the audio does it gives you this runtime error
`
Methods marked with @UiThread must be executed on the main thread. Current thread: AudioPlayer`

If yes try this solution #29 it worked for me

**Comment by rowild** [comment]
@amrabdalkrim Your are fantastic, sir! Thank you so much!
