### ISSUE TITLE
Visualizer error

### ISSUE THREAD

**Issue by rowild** [matthew-carroll/fluttery_audio#31]
When starting to implement the Visualiztr functionality, I soon get the errror:

```
E/AudioEffect( 3269): set(): AudioFlinger could not create effect, status: -1
E/visualizers-JNI( 3269): Visualizer initCheck failed -3
E/Visualizer-JAVA( 3269): Error code -3 when initializing Visualizer.
E/MethodChannel#fluttery_audio_visualizer( 3269): Failed to handle method call
E/MethodChannel#fluttery_audio_visualizer( 3269): java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at io.fluttery.flutteryaudio.AudioVisualizer.activate(AudioVisualizer.java:22)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at io.fluttery.flutteryaudio.FlutteryAudioPlugin$FlutteryAudioVisualizerPlugin.onMethodCall(FlutteryAudioPlugin.java:220)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#fluttery_audio_visualizer( 3269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/EGL_emulation( 3269): eglMakeCurrent: 0xae494660: ver 3 0 (tinfo 0xae492780)
```

**Comment by rowild** [comment]
@amrabdalkrim Did you happen to run into this error, too?

**Comment by amrabdalkrim** [comment]
@rowild Did you check for the Audio permissions in your flutter activity in your generated android project?

**Comment by rowild** [comment]
@amrabdalkrim Thank you for your feedback! Indeed, I forgot to setup the permissions (uses-permissions), when I setup the project anew to build with Kotlin...

But after accepting the Audio dialog, I still had to restart the app to make it work (e.g. the album cover only had the background color, the play/pause button had its inactive "music note" icon..., tested on a Pixel 3 with API 27). I assume this should not be the eventual behaviour, right? How could that be solved?

**Comment by amrabdalkrim** [comment]
@rowild Maybe because you didn't specify permission for using the internet in your **android_manifest.xml** or the streaming URL is broken and you should change it or test it in another streaming player

> the play/pause button had its inactive "music note" icon

In general, this behavior comes when the player can't reach the stream and it's initializing.

**Comment by rowild** [comment]
@amrabdalkrim Once the permissions are set and the app is restarted, everythinig works fine. But it is that very problem of asking the user for the permission, then receiving the permission, and then continue working and loading the url of the first song instead of closing it down and restarting it again. I don't know, if I express myself clearly enough, but I hope you understand, what I mean. This is, what I would love to improve, but I have no clue as to how to do that. Any hints?
