### ISSUE TITLE
App Crashes After Syncing Files

### ISSUE THREAD

**Issue by rajeshjeshar** [matthew-carroll/fluttery_audio#6]
Console Log:
```
Launching lib\main.dart on Redmi 4 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
compiler message: file:///C:/Program%20Files/Flutter/.pub-cache/hosted/pub.dartlang.org/fluttery-0.0.5/lib/src/radial_drag_gesture_detector.dart:101:32: Error: Getter not found: 'PI'.
compiler message:         + ' at ${(angle / (2 * PI) * 360).toStringAsFixed(2)}°';
compiler message:                                ^^
compiler message: file:///C:/Program%20Files/Flutter/.pub-cache/hosted/pub.dartlang.org/fluttery-0.0.5/lib/src/radial_drag_gesture_detector.dart:101:32: Error: The getter 'PI' isn't defined for the class '#lib1::PolarCoord'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'PI'.
compiler message:         + ' at ${(angle / (2 * PI) * 360).toStringAsFixed(2)}°';
compiler message:                                ^
D/FlutteryAudioPlugin(17715): Flutter -> Android: audioplayer/demo_player/activate_visualizer
D/FlutteryAudioPlugin(17715): AudioPlayerCall - Player ID: demo_player, Command: activate_visualizer
D/FlutteryAudioPlugin(17715): Flutter -> Android: audioplayer/demo_player/load
D/FlutteryAudioPlugin(17715): AudioPlayerCall - Player ID: demo_player, Command: load
D/FlutteryAudioPlugin(17715): Loading new audio.
D/AudioPlayer(17715): load()
D/FlutteryAudioPlugin(17715): Android -> Flutter: onAudioLoading()
D/NetworkSecurityConfig(17715): No Network Security Config specified, using platform default
D/FlutteryAudioPlugin(17715): AudioVisualizerPlayerCall - Command: activate_visualizer
D/FlutteryAudioPlugin(17715): Activating visualizer
E/AudioEffect(17715): set(): AudioFlinger could not create effect, status: -1
E/visualizers-JNI(17715): Visualizer initCheck failed -3
E/Visualizer-JAVA(17715): Error code -3 when initializing Visualizer.
E/MethodChannel#fluttery_audio_visualizer(17715): Failed to handle method call
E/MethodChannel#fluttery_audio_visualizer(17715): java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
E/MethodChannel#fluttery_audio_visualizer(17715): 	at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at io.fluttery.flutteryaudio.AudioVisualizer.activate(AudioVisualizer.java:22)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at io.fluttery.flutteryaudio.FlutteryAudioPlugin$FlutteryAudioVisualizerPlugin.onMethodCall(FlutteryAudioPlugin.java:220)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:165)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at android.app.ActivityThread.main(ActivityThread.java:6228)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/MethodChannel#fluttery_audio_visualizer(17715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
D/AudioPlayer(17715): onBufferingUpdate(): 0%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 7%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onPrepared()
D/FlutteryAudioPlugin(17715): Android -> Flutter: onAudioReady()
D/FlutteryAudioPlugin(17715): Android -> Flutter: onPlayerPaused()
D/AudioPlayer(17715): onBufferingUpdate(): 18%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 28%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 39%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 46%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 57%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 67%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 78%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
D/AudioPlayer(17715): onBufferingUpdate(): 100%
D/FlutteryAudioPlugin(17715): Android -> Flutter: onBufferingUpdate()
Application finished.

```

**Comment by suburbanworrier** [comment]
@rajeshjeshar 
line 3 of your debug output lets you know that this is an issue with fluttery-0.0.5 rather than fluttery_audio

`compiler message: file:///C:/Program%20Files/Flutter/.pub-cache/hosted/pub.dartlang.org/fluttery-0.0.5/lib/src/radial_drag_gesture_detector.dart:101:32: Error: Getter not found: 'PI'.`

I suggest you close this issue (if that's possible) and raise another over at https://github.com/matthew-carroll/fluttery/issues if you still have the problem.
